import{afterEach,describe,expect,it}from"vitest";
import fs from"node:fs";import os from"node:os";import path from"node:path";
import{openDatabase}from"../db";import type{Config}from"../config";
const dirs:string[]=[];
function database(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"diaz-memory-"));dirs.push(root);const config={root,dataDir:path.join(root,"data"),artifactDir:path.join(root,"artifacts"),uploadDir:path.join(root,"uploads")}as Config;return openDatabase(config)}
afterEach(()=>{for(const d of dirs.splice(0))fs.rmSync(d,{recursive:true,force:true})});
describe("conversation memory",()=>{
 it("persists ordered turns and connects jobs to conversations",()=>{const db=database();const c=db.createConversation(crypto.randomUUID(),"New conversation");const j=db.createJob({id:crypto.randomUUID(),kind:"chat",prompt:"Remember the blue folder",conversationId:c.id,fileIds:[]});db.addMessage({id:crypto.randomUUID(),conversationId:c.id,role:"assistant",content:"I will remember it.",jobId:j.id});expect(db.listMessages(c.id).map(m=>m.content)).toEqual(["Remember the blue folder","I will remember it."]);expect(db.getJob(j.id)?.conversationId).toBe(c.id);expect(db.getConversation(c.id)?.title).toBe("Remember the blue folder");db.close()});
 it("keeps five detailed conversations and archives overflow",()=>{const db=database();for(let i=1;i<=6;i++)db.createConversation(crypto.randomUUID(),`Conversation ${i}`);const overflow=db.archiveOverflow();expect(overflow).toHaveLength(1);const archived=overflow[0]!;db.setConversationSummary(archived.id,"Durable compact summary");const rows=db.listConversations();expect(rows.filter(c=>c.status==="active")).toHaveLength(5);expect(rows.find(c=>c.id===archived.id)?.summary).toBe("Durable compact summary");db.close()});
 it("persists provider linkage for approval continuation",()=>{const db=database();const c=db.createConversation(crypto.randomUUID(),"Action");const j=db.createJob({id:crypto.randomUUID(),kind:"chat",prompt:"Perform the approved action",conversationId:c.id,fileIds:[]});const id=crypto.randomUUID();db.createApproval({id,jobId:j.id,tool:"calendar:create",summary:"Create event",argumentsJson:'{"title":"Review"}',providerItemId:"mcpr_test",providerResponseId:"resp_test"});expect(db.getApproval(id)).toMatchObject({jobId:j.id,status:"pending",providerItemId:"mcpr_test",providerResponseId:"resp_test"});db.decideApproval(id,"approved");expect(db.getApproval(id)?.status).toBe("approved");db.close()});
 it("retries without duplicating the failed user message",()=>{const db=database();const c=db.createConversation(crypto.randomUUID(),"Retry");db.createJob({id:crypto.randomUUID(),kind:"chat",prompt:"Please identify yourself",conversationId:c.id,fileIds:[]});db.createJob({id:crypto.randomUUID(),kind:"chat",prompt:"Please identify yourself",conversationId:c.id,fileIds:[],recordUserMessage:false});expect(db.listMessages(c.id).filter(m=>m.role==="user").map(m=>m.content)).toEqual(["Please identify yourself"]);db.close()});
});
