import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{api,type ArtifactView,type ApprovalView,type UploadView,type SkillView}from"./api";
import type{JobKind,JobView,ConversationView,MessageView}from"../shared/contracts";
import"./styles.css";
import"./chat.css";

const kinds:{id:JobKind;label:string;hint:string}[]=[
  {id:"chat",label:"Chat",hint:"Reason and answer"},{id:"research",label:"Research",hint:"Current, cited synthesis"},
  {id:"analysis",label:"Analyze",hint:"Run code on uploaded files"},{id:"presentation",label:"Slides",hint:"Validated PowerPoint"},
  {id:"document",label:"Document",hint:"Finished Word report"},{id:"website",label:"Website",hint:"Responsive site ZIP"}
];

function Login({onDone}:{onDone:()=>void}){const[p,setP]=useState("");const[e,setE]=useState("");const[busy,setBusy]=useState(false);return <main className="login"><form onSubmit={async x=>{x.preventDefault();setBusy(true);setE("");try{await api.login(p);onDone()}catch(err){setE((err as Error).message)}finally{setBusy(false)}}}><div className="seal">D</div><p className="eyebrow">REVIVED • SECURE • 2026</p><h1>Agent Díaz</h1><p>Your private artifact and research workbench.</p><label>Owner passphrase<input type="password" value={p} onChange={e=>setP(e.target.value)} autoFocus minLength={16} required/></label>{e&&<p className="error">{e}</p>}<button disabled={busy}>{busy?"Opening…":"Enter workspace"}</button></form></main>}

function App(){
 const[ready,setReady]=useState<boolean|null>(null),[jobs,setJobs]=useState<JobView[]>([]),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<(JobView&{artifacts:ArtifactView[];approvals:ApprovalView[]})|null>(null),[conversations,setConversations]=useState<ConversationView[]>([]),[conversationId,setConversationId]=useState<string|null>(null),[messages,setMessages]=useState<MessageView[]>([]);const[kind,setKind]=useState<JobKind>("chat"),[prompt,setPrompt]=useState(""),[uploads,setUploads]=useState<UploadView[]>([]),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 const[skills,setSkills]=useState<SkillView[]>([]);
 const refresh=async()=>{try{const [list,convos]=await Promise.all([api.jobs(),api.conversations()]);setJobs(list);setConversations(convos);if(selected)setDetail(await api.job(selected));if(conversationId)setMessages((await api.conversation(conversationId)).messages)}catch(error){const message=error instanceof Error?error.message:"Workspace refresh failed";console.error("workspace.refresh_failed",error);setErr(`Connection problem: ${message}`)}};
 useEffect(()=>{api.session().then(()=>setReady(true)).catch(()=>setReady(false))},[]);
 useEffect(()=>{if(!ready)return;void refresh();void api.skills().then(setSkills).catch(error=>{console.error("skills.load_failed",error);setErr("Díaz could not load the capability list.")});const t=setInterval(()=>void refresh(),1800);return()=>clearInterval(t)},[ready,selected,conversationId]);
 const current=useMemo(()=>detail??jobs.find(j=>j.id===selected)??null,[detail,jobs,selected]);
 const conversation=conversations.find(c=>c.id===conversationId);
 const returnToConversation=async()=>{setSelected(null);setDetail(null);if(conversationId)setMessages((await api.conversation(conversationId)).messages)};
 if(ready===null)return <div className="boot">Waking Agent Díaz…</div>;if(!ready)return <Login onDone={()=>setReady(true)}/>;
 return <div className="shell">
  <aside className="rail"><div><div className="brand"><span>D</span><div><strong>Agent Díaz</strong><small>Persistent memory</small></div></div><button className="new" onClick={async()=>{const c=await api.createConversation();setConversationId(c.id);setMessages([]);setSelected(null);setDetail(null);await refresh()}}>+ New conversation</button><nav>{conversations.map(c=><button key={c.id} className={conversationId===c.id?"active":""} onClick={async()=>{setConversationId(c.id);setSelected(null);setDetail(null);setMessages((await api.conversation(c.id)).messages)}}><span className={`dot ${c.status==="active"?"completed":""}`}/><b>{c.title}</b><small>{c.status==="archived"?"Archived summary":`${c.messageCount} messages`}</small></button>)}</nav></div><button className="logout" onClick={async()=>{await api.logout();setReady(false)}}>Sign out</button></aside>
  <main className="workspace"><header className="workspaceHeader"><div><p className="eyebrow">PRIVATE AGENT WORKSPACE</p><h1>{conversationId?"Conversation":"Start a conversation"}</h1>{conversation&&<p className="conversationTitle" title={conversation.title}>{conversation.title}</p>}</div><details className="skillsPanel"><summary>Capabilities <span>{skills.length}</span></summary><div>{skills.map(s=><article key={s.id}><b>{s.name}</b><small>{s.description}</small></article>)}</div></details></header>
   {!current?<section className="composer">{conversationId&&<div className="chatlog">{messages.map(m=><div key={m.id} className={`bubble ${m.role}`}><b>{m.role==="user"?"You":"Díaz"}</b><p>{m.content}</p></div>)}</div>}<div className="kinds">{kinds.map(k=><button key={k.id} className={kind===k.id?"active":""} onClick={()=>setKind(k.id)}><b>{k.label}</b><small>{k.hint}</small></button>)}</div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={conversationId?"Continue the conversation…":"Create a conversation to begin."} rows={5} disabled={!conversationId}/><div className="uploadRow"><label className="fileButton">Attach files<input type="file" multiple onChange={async e=>{if(!e.target.files?.length)return;setBusy(true);setErr("");try{const added=await api.upload([...e.target.files]);setUploads(u=>[...u,...added])}catch(x){setErr((x as Error).message)}finally{setBusy(false)}}}/></label><div>{uploads.map(u=><span className="chip" key={u.id}>{u.name}</span>)}</div></div>{err&&<p className="error">{err}</p>}<button className="run" disabled={busy||!conversationId||prompt.trim().length<2} onClick={async()=>{setBusy(true);setErr("");try{const j=await api.createJob({prompt,kind,fileIds:uploads.map(u=>u.id),conversationId:conversationId!});setSelected(j.id);setPrompt("");setUploads([])}catch(x){setErr((x as Error).message)}finally{setBusy(false)}}}>{busy?"Working…":"Send to Díaz"}</button></section>:
   <section className="result"><div className="statusCard"><div className="statusTop"><span className={`pill ${current.status}`}>{current.status.replace("_"," ")}</span><strong>{current.progress}%</strong></div><div className="bar"><i style={{width:`${current.progress}%`}}/></div><p>{current.message}</p>{!["completed","failed","cancelled"].includes(current.status)&&<button className="danger" onClick={()=>api.cancel(current.id)}>Cancel task</button>}{current.error&&<pre className="errorbox">{current.error}</pre>}</div>
   {detail?.approvals.map(a=><div className="approval" key={a.id}><p className="eyebrow">APPROVAL REQUIRED</p><h2>{a.tool}</h2><p>{a.summary}</p><pre>{JSON.stringify(a.arguments,null,2)}</pre><div><button onClick={()=>api.decide(a.id,"approved")}>Approve once</button><button className="danger" onClick={()=>api.decide(a.id,"rejected")}>Reject</button></div></div>)}
   {!!detail?.artifacts.length&&<div className="artifacts"><h2>Artifacts</h2>{detail.artifacts.map(a=><a key={a.id} href={`/api/artifacts/${a.id}/download`}><span>↓</span><div><b>{a.name}</b><small>{(a.size/1024).toFixed(1)} KB • validated</small></div></a>)}</div>}
   {current.outputText&&<article><h2>Agent result</h2><pre>{current.outputText}</pre></article>}
   <div className="resultActions">{["failed","cancelled"].includes(current.status)&&<button className="run" disabled={busy} onClick={async()=>{setBusy(true);setErr("");try{const retried=await api.retry(current.id);setSelected(retried.id);setDetail(null)}catch(error){setErr(error instanceof Error?error.message:"Retry failed")}finally{setBusy(false)}}}>{busy?"Retrying…":"Retry task"}</button>}<button className="new" onClick={()=>void returnToConversation()}>Back to conversation</button></div>{err&&<p className="error">{err}</p>}</section>}
  </main>
 </div>
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
